config/routes.rb
Rails.application.routes.draw do
  get 'about-us', to: 'about#index', as: :about
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create" # Sends email(?)
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  
  get '/auth/twitter2/callback', to: 'sessions#create'
 
  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "Must be valid email." }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        if session[:user_id] 
            Current.user = User.find(session[:user_id])
        end
    end
    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController 
    def index
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end
    def create 
        @user = User.find_by(email: params[:email])
        if @user.present?
            #Send email
            PasswordMailer.with(user: @user).reset.deliver_later
        end    
        redirect_to root_path, notice: "We sent link to your email to reset password."     
    end
    def edit 
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token for reset password has expired."
    end
    def update 
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully. Please log in."
        else
            redirect_to edit_password_path
        end
    end
    private
    def password_params 
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit 
    end
    def update 
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password changed successfully!"
        else
            redirect_to edit_password_path, alert: "Password is not changed!"
        end
    end
    private
    def password_params 
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully registered!"
        else                   
            redirect_to sign_up_path, alert: "Something was not right with your registration."
        end
    end
    private
    def user_params 
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    def create         
        Current.user = User.find_by(email: params[:email])
        if Current.user.present? && Current.user.authenticate(params[:password])
            session[:user_id] = Current.user.id
            redirect_to root_path, notice: "You are logged in."
        else
            redirect_to sign_in_path, alert: "Invalid email or password."
        end
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "You are logged out."
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
app\views\about\index.html.erb
<h3>And here we are</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
app\views\main\index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h3>Welcome to scheduled_tweets</h3>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "confirm password" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password?</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control", placeholder: "type@email.com" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">    
    <%= link_to "Schedule Tweets", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">        
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>          
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>        
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>        
          </li>
        <% end %> 
      </ul>
    </div>
  </div>
</nav>